//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWpfApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Epizod", Namespace="http://schemas.datacontract.org/2004/07/SorozatServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Epizod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HosszField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cim {
            get {
                return this.CimField;
            }
            set {
                if ((object.ReferenceEquals(this.CimField, value) != true)) {
                    this.CimField = value;
                    this.RaisePropertyChanged("Cim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hossz {
            get {
                return this.HosszField;
            }
            set {
                if ((this.HosszField.Equals(value) != true)) {
                    this.HosszField = value;
                    this.RaisePropertyChanged("Hossz");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISorozatService")]
    public interface ISorozatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorozatService/Sorozatok", ReplyAction="http://tempuri.org/ISorozatService/SorozatokResponse")]
        string[] Sorozatok();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorozatService/Sorozatok", ReplyAction="http://tempuri.org/ISorozatService/SorozatokResponse")]
        System.Threading.Tasks.Task<string[]> SorozatokAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorozatService/Epizodok", ReplyAction="http://tempuri.org/ISorozatService/EpizodokResponse")]
        ClientWpfApp.ServiceReference1.Epizod[] Epizodok(string cim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISorozatService/Epizodok", ReplyAction="http://tempuri.org/ISorozatService/EpizodokResponse")]
        System.Threading.Tasks.Task<ClientWpfApp.ServiceReference1.Epizod[]> EpizodokAsync(string cim);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISorozatServiceChannel : ClientWpfApp.ServiceReference1.ISorozatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SorozatServiceClient : System.ServiceModel.ClientBase<ClientWpfApp.ServiceReference1.ISorozatService>, ClientWpfApp.ServiceReference1.ISorozatService {
        
        public SorozatServiceClient() {
        }
        
        public SorozatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SorozatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SorozatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SorozatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Sorozatok() {
            return base.Channel.Sorozatok();
        }
        
        public System.Threading.Tasks.Task<string[]> SorozatokAsync() {
            return base.Channel.SorozatokAsync();
        }
        
        public ClientWpfApp.ServiceReference1.Epizod[] Epizodok(string cim) {
            return base.Channel.Epizodok(cim);
        }
        
        public System.Threading.Tasks.Task<ClientWpfApp.ServiceReference1.Epizod[]> EpizodokAsync(string cim) {
            return base.Channel.EpizodokAsync(cim);
        }
    }
}
