//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentProject.MNBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mnb.hu/webservices/", ConfigurationName="MNBService.MNBArfolyamServiceSoap")]
    public interface MNBArfolyamServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetInfoResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetInfo", ReplyAction="*")]
        CurrentProject.MNBService.GetInfoResponse GetInfo(CurrentProject.MNBService.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetInfoResponse> GetInfoAsync(CurrentProject.MNBService.GetInfoRequest request);
        
        // CODEGEN: Generating message contract since element name GetCurrentExchangeRatesResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrentExchangeRates", ReplyAction="*")]
        CurrentProject.MNBService.GetCurrentExchangeRatesResponse GetCurrentExchangeRates(CurrentProject.MNBService.GetCurrentExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrentExchangeRates", ReplyAction="*")]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(CurrentProject.MNBService.GetCurrentExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since element name startDate from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetExchangeRates", ReplyAction="*")]
        CurrentProject.MNBService.GetExchangeRatesResponse GetExchangeRates(CurrentProject.MNBService.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetExchangeRates", ReplyAction="*")]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetExchangeRatesResponse> GetExchangeRatesAsync(CurrentProject.MNBService.GetExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since element name GetDateIntervalResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetDateInterval", ReplyAction="*")]
        CurrentProject.MNBService.GetDateIntervalResponse GetDateInterval(CurrentProject.MNBService.GetDateIntervalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetDateInterval", ReplyAction="*")]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetDateIntervalResponse> GetDateIntervalAsync(CurrentProject.MNBService.GetDateIntervalRequest request);
        
        // CODEGEN: Generating message contract since element name GetCurrenciesResult from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencies", ReplyAction="*")]
        CurrentProject.MNBService.GetCurrenciesResponse GetCurrencies(CurrentProject.MNBService.GetCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencies", ReplyAction="*")]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetCurrenciesResponse> GetCurrenciesAsync(CurrentProject.MNBService.GetCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since element name currencyNames from namespace http://www.mnb.hu/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencyUnits", ReplyAction="*")]
        CurrentProject.MNBService.GetCurrencyUnitsResponse GetCurrencyUnits(CurrentProject.MNBService.GetCurrencyUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/GetCurrencyUnits", ReplyAction="*")]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(CurrentProject.MNBService.GetCurrencyUnitsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfo", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetInfoRequestBody Body;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(CurrentProject.MNBService.GetInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInfoRequestBody {
        
        public GetInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetInfoResponseBody Body;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(CurrentProject.MNBService.GetInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoResult;
        
        public GetInfoResponseBody() {
        }
        
        public GetInfoResponseBody(string GetInfoResult) {
            this.GetInfoResult = GetInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRates", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetCurrentExchangeRatesRequestBody Body;
        
        public GetCurrentExchangeRatesRequest() {
        }
        
        public GetCurrentExchangeRatesRequest(CurrentProject.MNBService.GetCurrentExchangeRatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrentExchangeRatesRequestBody {
        
        public GetCurrentExchangeRatesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetCurrentExchangeRatesResponseBody Body;
        
        public GetCurrentExchangeRatesResponse() {
        }
        
        public GetCurrentExchangeRatesResponse(CurrentProject.MNBService.GetCurrentExchangeRatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrentExchangeRatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentExchangeRatesResult;
        
        public GetCurrentExchangeRatesResponseBody() {
        }
        
        public GetCurrentExchangeRatesResponseBody(string GetCurrentExchangeRatesResult) {
            this.GetCurrentExchangeRatesResult = GetCurrentExchangeRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRates", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetExchangeRatesRequestBody Body;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(CurrentProject.MNBService.GetExchangeRatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetExchangeRatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string currencyNames;
        
        public GetExchangeRatesRequestBody() {
        }
        
        public GetExchangeRatesRequestBody(string startDate, string endDate, string currencyNames) {
            this.startDate = startDate;
            this.endDate = endDate;
            this.currencyNames = currencyNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetExchangeRatesResponseBody Body;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(CurrentProject.MNBService.GetExchangeRatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetExchangeRatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesResult;
        
        public GetExchangeRatesResponseBody() {
        }
        
        public GetExchangeRatesResponseBody(string GetExchangeRatesResult) {
            this.GetExchangeRatesResult = GetExchangeRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateInterval", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetDateIntervalRequestBody Body;
        
        public GetDateIntervalRequest() {
        }
        
        public GetDateIntervalRequest(CurrentProject.MNBService.GetDateIntervalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDateIntervalRequestBody {
        
        public GetDateIntervalRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateIntervalResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetDateIntervalResponseBody Body;
        
        public GetDateIntervalResponse() {
        }
        
        public GetDateIntervalResponse(CurrentProject.MNBService.GetDateIntervalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetDateIntervalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDateIntervalResult;
        
        public GetDateIntervalResponseBody() {
        }
        
        public GetDateIntervalResponseBody(string GetDateIntervalResult) {
            this.GetDateIntervalResult = GetDateIntervalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencies", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetCurrenciesRequestBody Body;
        
        public GetCurrenciesRequest() {
        }
        
        public GetCurrenciesRequest(CurrentProject.MNBService.GetCurrenciesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrenciesRequestBody {
        
        public GetCurrenciesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrenciesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetCurrenciesResponseBody Body;
        
        public GetCurrenciesResponse() {
        }
        
        public GetCurrenciesResponse(CurrentProject.MNBService.GetCurrenciesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrenciesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrenciesResult;
        
        public GetCurrenciesResponseBody() {
        }
        
        public GetCurrenciesResponseBody(string GetCurrenciesResult) {
            this.GetCurrenciesResult = GetCurrenciesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnits", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetCurrencyUnitsRequestBody Body;
        
        public GetCurrencyUnitsRequest() {
        }
        
        public GetCurrencyUnitsRequest(CurrentProject.MNBService.GetCurrencyUnitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrencyUnitsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string currencyNames;
        
        public GetCurrencyUnitsRequestBody() {
        }
        
        public GetCurrencyUnitsRequestBody(string currencyNames) {
            this.currencyNames = currencyNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnitsResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public CurrentProject.MNBService.GetCurrencyUnitsResponseBody Body;
        
        public GetCurrencyUnitsResponse() {
        }
        
        public GetCurrencyUnitsResponse(CurrentProject.MNBService.GetCurrencyUnitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mnb.hu/webservices/")]
    public partial class GetCurrencyUnitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrencyUnitsResult;
        
        public GetCurrencyUnitsResponseBody() {
        }
        
        public GetCurrencyUnitsResponseBody(string GetCurrencyUnitsResult) {
            this.GetCurrencyUnitsResult = GetCurrencyUnitsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MNBArfolyamServiceSoapChannel : CurrentProject.MNBService.MNBArfolyamServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MNBArfolyamServiceSoapClient : System.ServiceModel.ClientBase<CurrentProject.MNBService.MNBArfolyamServiceSoap>, CurrentProject.MNBService.MNBArfolyamServiceSoap {
        
        public MNBArfolyamServiceSoapClient() {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CurrentProject.MNBService.GetInfoResponse CurrentProject.MNBService.MNBArfolyamServiceSoap.GetInfo(CurrentProject.MNBService.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public string GetInfo() {
            CurrentProject.MNBService.GetInfoRequest inValue = new CurrentProject.MNBService.GetInfoRequest();
            inValue.Body = new CurrentProject.MNBService.GetInfoRequestBody();
            CurrentProject.MNBService.GetInfoResponse retVal = ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetInfo(inValue);
            return retVal.Body.GetInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetInfoResponse> CurrentProject.MNBService.MNBArfolyamServiceSoap.GetInfoAsync(CurrentProject.MNBService.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CurrentProject.MNBService.GetInfoResponse> GetInfoAsync() {
            CurrentProject.MNBService.GetInfoRequest inValue = new CurrentProject.MNBService.GetInfoRequest();
            inValue.Body = new CurrentProject.MNBService.GetInfoRequestBody();
            return ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CurrentProject.MNBService.GetCurrentExchangeRatesResponse CurrentProject.MNBService.MNBArfolyamServiceSoap.GetCurrentExchangeRates(CurrentProject.MNBService.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRates(request);
        }
        
        public string GetCurrentExchangeRates() {
            CurrentProject.MNBService.GetCurrentExchangeRatesRequest inValue = new CurrentProject.MNBService.GetCurrentExchangeRatesRequest();
            inValue.Body = new CurrentProject.MNBService.GetCurrentExchangeRatesRequestBody();
            CurrentProject.MNBService.GetCurrentExchangeRatesResponse retVal = ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRates(inValue);
            return retVal.Body.GetCurrentExchangeRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetCurrentExchangeRatesResponse> CurrentProject.MNBService.MNBArfolyamServiceSoap.GetCurrentExchangeRatesAsync(CurrentProject.MNBService.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CurrentProject.MNBService.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync() {
            CurrentProject.MNBService.GetCurrentExchangeRatesRequest inValue = new CurrentProject.MNBService.GetCurrentExchangeRatesRequest();
            inValue.Body = new CurrentProject.MNBService.GetCurrentExchangeRatesRequestBody();
            return ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CurrentProject.MNBService.GetExchangeRatesResponse CurrentProject.MNBService.MNBArfolyamServiceSoap.GetExchangeRates(CurrentProject.MNBService.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public string GetExchangeRates(string startDate, string endDate, string currencyNames) {
            CurrentProject.MNBService.GetExchangeRatesRequest inValue = new CurrentProject.MNBService.GetExchangeRatesRequest();
            inValue.Body = new CurrentProject.MNBService.GetExchangeRatesRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.currencyNames = currencyNames;
            CurrentProject.MNBService.GetExchangeRatesResponse retVal = ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetExchangeRates(inValue);
            return retVal.Body.GetExchangeRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetExchangeRatesResponse> CurrentProject.MNBService.MNBArfolyamServiceSoap.GetExchangeRatesAsync(CurrentProject.MNBService.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CurrentProject.MNBService.GetExchangeRatesResponse> GetExchangeRatesAsync(string startDate, string endDate, string currencyNames) {
            CurrentProject.MNBService.GetExchangeRatesRequest inValue = new CurrentProject.MNBService.GetExchangeRatesRequest();
            inValue.Body = new CurrentProject.MNBService.GetExchangeRatesRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            inValue.Body.currencyNames = currencyNames;
            return ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CurrentProject.MNBService.GetDateIntervalResponse CurrentProject.MNBService.MNBArfolyamServiceSoap.GetDateInterval(CurrentProject.MNBService.GetDateIntervalRequest request) {
            return base.Channel.GetDateInterval(request);
        }
        
        public string GetDateInterval() {
            CurrentProject.MNBService.GetDateIntervalRequest inValue = new CurrentProject.MNBService.GetDateIntervalRequest();
            inValue.Body = new CurrentProject.MNBService.GetDateIntervalRequestBody();
            CurrentProject.MNBService.GetDateIntervalResponse retVal = ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetDateInterval(inValue);
            return retVal.Body.GetDateIntervalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetDateIntervalResponse> CurrentProject.MNBService.MNBArfolyamServiceSoap.GetDateIntervalAsync(CurrentProject.MNBService.GetDateIntervalRequest request) {
            return base.Channel.GetDateIntervalAsync(request);
        }
        
        public System.Threading.Tasks.Task<CurrentProject.MNBService.GetDateIntervalResponse> GetDateIntervalAsync() {
            CurrentProject.MNBService.GetDateIntervalRequest inValue = new CurrentProject.MNBService.GetDateIntervalRequest();
            inValue.Body = new CurrentProject.MNBService.GetDateIntervalRequestBody();
            return ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetDateIntervalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CurrentProject.MNBService.GetCurrenciesResponse CurrentProject.MNBService.MNBArfolyamServiceSoap.GetCurrencies(CurrentProject.MNBService.GetCurrenciesRequest request) {
            return base.Channel.GetCurrencies(request);
        }
        
        public string GetCurrencies() {
            CurrentProject.MNBService.GetCurrenciesRequest inValue = new CurrentProject.MNBService.GetCurrenciesRequest();
            inValue.Body = new CurrentProject.MNBService.GetCurrenciesRequestBody();
            CurrentProject.MNBService.GetCurrenciesResponse retVal = ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetCurrencies(inValue);
            return retVal.Body.GetCurrenciesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetCurrenciesResponse> CurrentProject.MNBService.MNBArfolyamServiceSoap.GetCurrenciesAsync(CurrentProject.MNBService.GetCurrenciesRequest request) {
            return base.Channel.GetCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CurrentProject.MNBService.GetCurrenciesResponse> GetCurrenciesAsync() {
            CurrentProject.MNBService.GetCurrenciesRequest inValue = new CurrentProject.MNBService.GetCurrenciesRequest();
            inValue.Body = new CurrentProject.MNBService.GetCurrenciesRequestBody();
            return ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetCurrenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CurrentProject.MNBService.GetCurrencyUnitsResponse CurrentProject.MNBService.MNBArfolyamServiceSoap.GetCurrencyUnits(CurrentProject.MNBService.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnits(request);
        }
        
        public string GetCurrencyUnits(string currencyNames) {
            CurrentProject.MNBService.GetCurrencyUnitsRequest inValue = new CurrentProject.MNBService.GetCurrencyUnitsRequest();
            inValue.Body = new CurrentProject.MNBService.GetCurrencyUnitsRequestBody();
            inValue.Body.currencyNames = currencyNames;
            CurrentProject.MNBService.GetCurrencyUnitsResponse retVal = ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetCurrencyUnits(inValue);
            return retVal.Body.GetCurrencyUnitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CurrentProject.MNBService.GetCurrencyUnitsResponse> CurrentProject.MNBService.MNBArfolyamServiceSoap.GetCurrencyUnitsAsync(CurrentProject.MNBService.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CurrentProject.MNBService.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(string currencyNames) {
            CurrentProject.MNBService.GetCurrencyUnitsRequest inValue = new CurrentProject.MNBService.GetCurrencyUnitsRequest();
            inValue.Body = new CurrentProject.MNBService.GetCurrencyUnitsRequestBody();
            inValue.Body.currencyNames = currencyNames;
            return ((CurrentProject.MNBService.MNBArfolyamServiceSoap)(this)).GetCurrencyUnitsAsync(inValue);
        }
    }
}
