//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milestone
    {
        public Milestone()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int MilestoneId { get; set; }
        public string Name { get; set; }
        public int Scale { get; set; }
        public int MethodologyId { get; set; }
    
        public virtual Methodology Methodology { get; set; }
        public virtual ICollection<Task> Task { get; set; }
    }
}
