//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentProject.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Chat> Chat { get; set; }
        public DbSet<Difficulty> Difficulty { get; set; }
        public DbSet<Methodology> Methodology { get; set; }
        public DbSet<Milestone> Milestone { get; set; }
        public DbSet<Project> Project { get; set; }
        public DbSet<ProjectAttachment> ProjectAttachment { get; set; }
        public DbSet<ProjectMember> ProjectMember { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<SecurityQuestion> SecurityQuestion { get; set; }
        public DbSet<Task> Task { get; set; }
        public DbSet<TaskComment> TaskComment { get; set; }
        public DbSet<User> User { get; set; }
    }
}
