//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Chat = new HashSet<Chat>();
            this.ProjectAttachment = new HashSet<ProjectAttachment>();
            this.ProjectMember = new HashSet<ProjectMember>();
            this.Task = new HashSet<Task>();
        }
    
        public int ProjectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int DifficultyId { get; set; }
        public int MethodologyId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime RealEndDate { get; set; }
        public byte Active { get; set; }
        public System.DateTime Registered { get; set; }
    
        public virtual ICollection<Chat> Chat { get; set; }
        public virtual Difficulty Difficulty { get; set; }
        public virtual Methodology Methodology { get; set; }
        public virtual ICollection<ProjectAttachment> ProjectAttachment { get; set; }
        public virtual ICollection<ProjectMember> ProjectMember { get; set; }
        public virtual ICollection<Task> Task { get; set; }
    }
}
