//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.TaskComment = new HashSet<TaskComment>();
        }
    
        public int TaskId { get; set; }
        public int ProjectId { get; set; }
        public int MilestoneId { get; set; }
        public int UserId { get; set; }
        public string Task1 { get; set; }
        public string Description { get; set; }
        public byte Completed { get; set; }
        public System.DateTime CompletedDate { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Milestone Milestone { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<TaskComment> TaskComment { get; set; }
        public virtual User User { get; set; }
    }
}
