//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrentProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Chat = new HashSet<Chat>();
            this.ProjectAttachment = new HashSet<ProjectAttachment>();
            this.ProjectMember = new HashSet<ProjectMember>();
            this.Task = new HashSet<Task>();
            this.TaskComment = new HashSet<TaskComment>();
        }
    
        public int UserId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int SecurityQuestionId { get; set; }
        public string SecurityQuestionAnswer { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public System.DateTime Registered { get; set; }
    
        public virtual ICollection<Chat> Chat { get; set; }
        public virtual ICollection<ProjectAttachment> ProjectAttachment { get; set; }
        public virtual ICollection<ProjectMember> ProjectMember { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual ICollection<Task> Task { get; set; }
        public virtual ICollection<TaskComment> TaskComment { get; set; }
    }
}
